### ISSUE TITLE
No such file or directory: 'node_classification_results.csv'

### ISSUE THREAD

**Issue by cyang810** [wendli01/info_han#1]
could you upload the 'node_classification_results.csv', thanks!

**Comment by wendli01** [comment]
Thank you for pointing out this omission, seems it was in LFS and therefore not included in the fork from my private repo?
Anyway, I [added](https://github.com/wendli01/info_han/commit/d07afd4) [it](https://github.com/wendli01/info_han/blob/master/experiments/node_classification_results.csv) now and made sure that it is the final version that should reproduce the tables in the notebook.
